### ISSUE TITLE
CentOS 7 GLIB_2.18 not found

### ISSUE THREAD

**Issue by ebdavison** [r-darwish/topgrade#243]
When running topgrade in the default mode, the first thing that happens is that it upgrades itself. I h Normally fine until recently (and tested again today on a different CentOS 7 box), which results in an error following upgrade:
```
/home/edavison/topgrade: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/edavison/topgrade)
```
Not sure which version I currently have since an attempt to get the version also results in the same error.

CentOS version 7.7.1908

**Comment by ebdavison** [comment]
Did some more checking and topgrade version 3.0.0 runs without the GLIBC error but anything newer will not run at all even for `--help` or `--version`.
Is there a way to disable the self auto-update?

**Comment by r-darwish** [comment]
I have not added a way to disable it. I should do that. However, I prefer to solve your problem. When using a distribution with an old version of glibc, such as CentOS, I advise that you download `topgrade-v3.2.0-x86_64-unknown-linux-musl.tar.gz` instead of `topgrade-v3.2.0-x86_64-unknown-linux-gnu.tar.gz`, as the MUSL version doesn't depend on glibc. The MUSL version should self-update itself with a MUSL version is well. If it doesn't then it's a bug.

**Comment by r-darwish** [comment]
Closing in favor of #244

**Comment by ebdavison** [comment]
I will try the MUSL version.
