### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by tversteeg** [r-darwish/topgrade#34]
It would be really nice to be able to run this on Windows.

Suggested package managers:

- Chocolatey
- MSYS (Pacman)

**Comment by r-darwish** [comment]
I actually wanted to support Windows from the beginning and ran into issues, so I decided to postpone it until someone asks. Now that it happens, I'll specify the issues and we'll see how we can progress

# Issues
* The `git` command does not seem to follow symlinks in Windows. It means that if I have a single repository with all of my configuration, and links its `emacs` subdirectory in `~/.emacs.d`, Topgrade does not detect that as a git repository as it does in Unix. I have not checked whether [canonicalize](https://doc.rust-lang.org/std/path/struct.Path.html#method.canonicalize) follows symlinks in Windows, but if it does not then I'll probably have to make some specific Windows API call

* Termion doesn't support Windows at the moment. There's a fork which claims to support, but it is unmaintained. I think that I'll refactor the terminal module so that in Windows it won't use Termion features. This means we won't have colors in Windows, but it's a start

* I suspect that if Topgrade is installed using `cargo install`, then `cargo update-install` will always fail when ran by Topgrade because you can't replace a running executable in Windows. I have not checked it yet.

# Platform specific features
I'd like to support the following
* Chocolatey
* Update Powershell modules
* Add the Powershell configuration to the list of files to check if tracked by git
* Perform Windows update from Powershell

I'm not sure what should I for msys2. Should I just try to run Pacman? Would `pacman` appear in `PATH` for non mingw compiled applications ran from the msys2 terminal?

**Comment by tversteeg** [comment]
`pacman` is the command I use inside the msys2 shell, I found a [so question](https://stackoverflow.com/q/26809898/1350184) about how to use it from outside the shell.

**Comment by tversteeg** [comment]
How about using [rust-ansi-term](https://github.com/ogham/rust-ansi-term) for the colors instead of Termion?

**Comment by r-darwish** [comment]
Looking good. They don't support getting the size of the terminal, but there are other crates that do that which also work in Windows. I'll look into them.

**Comment by tversteeg** [comment]
I've also been looking for getting the elevation status of the current process, but I couldn't find any crate for it. It probably needs to be done manually with a script or the winapi crate.

**Comment by r-darwish** [comment]
Support has been added to the master branch. Topgrade can run Chocolatey on Windows as well as the other platform independent steps. I'm closing this issue in favor of more specific Windows issues.

**Comment by tversteeg** [comment]
That's quick, thanks a lot!
