### ISSUE TITLE
Enable features that are disabled by default

### ISSUE THREAD

**Issue by slotThe** [r-darwish/topgrade#406]
**I want to suggest some general feature**
I think having a general way of not only disabling commands, but also enabling some commands that may be turned off by default.  I.e. have a pool of `default-commands` that are enabled by default and, in addition to `--disable`, support some kind of `--enable` command. 

As an example use-case, take #389, where `tlmgr` was completely disabled for linux.  This is a problem insofar as that while this is the intended behaviour for many of linux distributions, some do rely on this tool to update tex related packages, consciously not packaging anything but texlive itself.   I would imagine this situation may crop up from time to time so that a general feature might be useful.

**Comment by r-darwish** [comment]
I'm not convinced we should do it.

While Topgrade is a configurable tool, it's philosophy is that it should do its best to make the reasonable choice. I don't see any generic reason why some steps should be turned off by default.

I disabled tlmgr completely on Linux because it seems like the right solution. However, if there's a non-esoteric scenario in which it makes sense to run it in Linux, we can discuss whether there's any method to detect that, and if so run tlmgr on Linux as well.

**Comment by slotThe** [comment]
On Tue, May 12 2020 13:10, Roey Darwish Dror wrote:
> While Topgrade is a configurable tool, it's philosophy is that it
> should do its best to make the reasonable choice. I don't see any
> generic reason why some steps should be turned off by default.
>

Alright, fair enough.

> I disabled tlmgr completely on Linux because it seems like the right
> solution. However, if there's a non-esoteric scenario in which it
> makes sense to run it in Linux, we can discuss whether there's any
> method to detect that, and if so run tlmgr on Linux as well.
>

A non-esoteric example would be Void Linux (which is already supported
by topgrade in the form of doing system updates via xbps-install); it
handles tex packages entirely through tlmgr.  Beyond hard coding
*something*, I don't see any good way whether a certain distribution
offers these packages---do you have any ideas there?  In addition to
that, there's also the problem of a user wanting to do things through
tlmgr even though the distribution they're using might also have the
respective packages in its repos.  I doubt that there's any automatic
solution here.

**Comment by ezickler** [comment]
I would love to have tlmgr as an option for linux. 
I just change my latex install from the rpm fedora repos to tlmgr because i don't want all the bloat of the 3000 texlive packages in my system updates all the time. And especially not when i do dist upgrades. 
Lexlive accounts easily for half of my packages other wise. 
So i thought of using topgrade as the solution as it gives me a place where i can update every thing if i want to while still having the other package manger when i want just as specific task.
So yeah i personally think this is a good feature to have.  

So i don't think this should be on by default, but definitely an option for those who prefer as self contained latex install. I think the ones how bother to install latex manually wouldn't mind to enable this manually.
