### ISSUE TITLE
Custom flags for emerge

### ISSUE THREAD

**Issue by remexre** [r-darwish/topgrade#423]
Topgrade should have an `emerge_flags` config option; not sure if it should augment or replace the existing emerge command lines. Maybe if replace, split this into `emerge_sync_flags` and `emerge_update_flags`?

**Comment by r-darwish** [comment]
Currently what we do with `yay_arguments` or `dnf_arguments` is that we append the given arguments to the arguments that we already run. Both don't have a designated "sync" command so there's no need for two configuration options.

Gentoo is pretty different, both because it needs to run two emerge commands, and that the emerge command contains quite a few arguments (`"-uDNa --with-bdeps=y world"`) so maybe complete override of that is a better option.
