### ISSUE TITLE
[Featuer request] docker and docker-compose pull for selected repos

### ISSUE THREAD

**Issue by Dzordzu** [r-darwish/topgrade#441]
I know that global pull is useless (as it was said in #214), but something like git repos will be quite a useful thing. Particularly I find it handful, when you want to remotely update system

Config example
```toml
[docker]
composes = [
   "/home/user/example-compose/"
]
images = [
   "mysql"
]
```

**Comment by r-darwish** [comment]
I'm still debating about that. Whenever I think about a feature in which you have to define the items to work on in the configuration file, I ask myself "what's the added value of making that a feature instead of just putting a custom commands in the configuration file?". 

I currently have two such features, which are vagrant and git. Their added values are:
*Git*:
1. Your custom repos are integrated with the automatically detected repos.
2. Everything is pulled in parallel, which you couldn't do with a custom command.

*Vagrant*: the added value is that Topgrade takes care of powering on and off your virtual boxes if they were off.

As for docker, I don't think parallel pulling is a good idea because docker pull is takes long time and parallel pulling means you won't see any progress bar, which is frustrating.

So I still can't think of a good enough added value which you won't get by just writing some docker pull commands as separated steps.

**Comment by Dzordzu** [comment]
For me it's more like organizing things in config. I'm currently using custom scripts, but this is just an ugly option. Repetition becomes overwhelming when you've got more containers. So better config is a first added value.
 
Futhermore, docker-compose parallelism option is not a bad idea. Especially, when you've got many small images.

The most important feature for me would be docker-compose. `docker pull` is quite useless (IMO) for a bigger scale nowadays ;) Just inserted it as proposal

**Comment by r-darwish** [comment]
If docker compose has built in parallelism by default then there's no added value for Topgrade. I'm keeping this open for more opinion, but at the moment it doesn't seem that Topgrade should do anything other than calling a pull command.
