### ISSUE TITLE
Update topgrade without root permissions

### ISSUE THREAD

**Issue by Jocomol** [r-darwish/topgrade#589]
Whenever I want to upgrade topgrade, I'll have to do this with root permissions. But the package manager of my distribution shouldn't be run as root (Pacman), so I have to ctrl+c the process after topgrade has been updated, this is very tiresome and it would be nice if I could just let it run and be assured that everything, including topgrade, will be updated.

**Comment by r-darwish** [comment]
Which distribution are you using where Pacman shouldn't be run as root?

**Comment by Jocomol** [comment]
Pardon me, I meant **yay**, the package manager for the AUR. I am using Manjaro.

Whenever I run topgrade with sudo, yay prints out the following message:

``-> Avoid running yay as root/sudo.``

**Comment by r-darwish** [comment]
That's weird. Topgrade shouldn't run yay with sudo. I use yay myself. Can you show me the output of `topgrade -v --only system`?

**Comment by r-darwish** [comment]
Oh. Now I understand. You're running topgrade as root because you want auto upgrade. Running Topgrade as sudo isn't recommended in any case. You have two other options:

1. Install Topgrade using yay and yay will take care of upgrading it
2. Use the binary release in Github which is compiled with the self-upgrade feature. If you do this then put the binary somewhere writable by your regular user (for example `~/.local/bin` so upgrading should work.

In any case, running Topgrade as root isn't recommended. I should probably put a warning about that.

**Comment by Jocomol** [comment]
Thank you I was able to fix it via yay on the manjaro machine and by putting the binaries in .local/bin on my raspis (the binaries were previously in /usr/local/bin, maybe you could add that to the documentation).

But now the remote topgrades don't work anymore:
env: ‘topgrade’: No such file or directory

**Comment by r-darwish** [comment]
There's a configuration file for that:

```toml
# Path to Topgrade executable on remote machines
remote_topgrade_path = ".cargo/bin/topgrade"
```

**Comment by Jocomol** [comment]
Nice, thank you, everything now works as intented
