### ISSUE TITLE
More update managers

### ISSUE THREAD

**Issue by trenkert** [r-darwish/topgrade#60]
Hi,

this is a great project!

could you include:

- texlive manager
- npm
- pip
- gem
- r
- cabal
- gnome extensions
- firefox extensions
- thunderbird extensions

**Comment by r-darwish** [comment]
Thank you!

- Texlive Manager - I'll look into that
- npm - Already implemented, but only if `npm root -g` is inside your home directory, because otherwise it can conflict with the system package manager, and Topgrade will not run it
- gem - Will do
- pip - Pip doesn't have the `--user-install` flag like gem does, nor can you set its root directory (at least that I know of). I don't to run it globally due to the same reason that I don't want to run NPM if its root directory is set outside you home directory
- r, cabal - I'll look into that
- Extensions - I'd love to, but I don't think there's a way to do that via the command line

**Comment by tversteeg** [comment]
The firefox extensions are self-updating in the latest versions.

**Comment by andytom** [comment]
> * pip - Pip doesn't have the --user-install flag like gem does, nor can you set its root directory (at least that I know of). I don't to run it globally due to the same reason that I don't want to run NPM if its root directory is set outside you home directory

I think you can do both with pip using the [--user](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-user) and/or the [--root](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-root) flags, I'm not sure when they were added so they might only be available in some versions.

**Comment by r-darwish** [comment]
@andytom I wasn't aware of that. Thanks! Opened #64 and #65. I'm keeping this issue opened as a "question" until I figure out what to do with cabal, r and texlive manager. Pull requests are also welcome :)

**Comment by bingalls** [comment]
I wrote https://github.com/bingalls/mac-tools and started work on a more cross-platform updater shell script. Frankly, topgrade is better, and I'm happy to send my work.
Also be sure to mention the companion Y-ppa manager on http://webupd8.org/ and I'll tell blog-master Andrew to plug for your project.
One nice feature of mac-tools, is that it summarizes new projects.

**Comment by r-darwish** [comment]
I'm closing this in favor of more specific issues. If you wish to have another package manager added, please open an issue and specify the exact commands that should be run.

**Comment by bdaase** [comment]
Updating gnome-shell extensions is possible. I opened https://github.com/r-darwish/topgrade/issues/755 with the exact command to use.
