### ISSUE TITLE
Unable to run node update since it is owned by root

### ISSUE THREAD

**Issue by amituttam** [r-darwish/topgrade#690]
Running topgrade on Debian linux and can't seem to get node upgrade to work:

```
$ topgrade --only node --verbose
―― 20:57:26 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
npm: SKIPPED: NPM root at /usr/local/lib/node_modules is owned by 0 which is not the current user
yarn: SKIPPED: Cannot find "yarn" in PATH
 2021-04-12T03:57:26.867Z DEBUG topgrade::terminal   > Desktop notification: Topgrade finished sucessfully
```

For system update topgrade prompts for sudo, for npm it doesn't look like it does (unsure if is expected to do so).

**Comment by r-darwish** [comment]
I chose this method on purpose because I don't think it's a good idea to run NPM as root, as it was probably intended to be upgraded by the system's package manager. If you think it does makes sense in some scenarios I can add a flag that will cause Topgrade to run NPM with sudo, but the default will remain not to do that.

**Comment by amituttam** [comment]
I think your proposal to add and option to run NPM as sudo but that the default will not do that makes sense.

**Comment by blackcat-917** [comment]
This could be useful to resolve the issue: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally.
