### ISSUE TITLE
Feature: packages list

### ISSUE THREAD

**Issue by flistell** [r-darwish/topgrade#735]
It would be nice if topgrade would be capable to LIST the packages from the package managers/steps it supports.
This could be super useful in case of "disaster recovery" or "new system installation".

Regards,
F.

**Comment by r-darwish** [comment]
Sorry, but this is way too much work at this point so I don't think it's in this tool's scope.

**Comment by andrei-pavel** [comment]
Sorry to post after close, but I just wanted to say that I also considered this useful and mentioned it once in here alongside an ability to install from said package list.

 If it were to be part of topgrade, it could also ensure that the packages are installed on every run. Just as an extra, this could potentially be turned into a more complex solution where the package list is uploaded to and fetched from a place in the cloud so that the user doesn't have to worry about maintaing the file containing the package list.

Anyway, the reason I think this is a good fit for topgrade is because it already has the ability to list, install, upgrade packages for so many package managers. So maybe we can find a way for this to work?

Consider this suggestion. What if this repo created another binary called `topstall` (we can work on the name) that will be able to:
* install a package and consider the best package manager to do it with, or ask the user interactively
* make a snapshot of the current packages and versions in the form of a readable text file, although versions are maybe less interesting, since we want to have everything updated all the time with tools coming from this repo
* install packages from a previously made snapshot

I mean look at what I'm doing to make that work right now. I keep the lists of packages under git:
```
$ ls ~/.config/packages/
apt.pkg  cargo.pkg  dnf.pkg  yay.pkg
```
And then I have scripts that save and load from these files:
```$ ls /usr/local/bin | grep -E 'load-|save-'
load-all-packages
load-apt-packages
load-cargo-crates
load-dnf-packages
load-pip-packages
load-pkg-packages
load-yay-packages
save-all-packages
save-apt-packages
save-cargo-crates
save-dnf-packages
save-pip-packages
save-pkg-packages
save-yay-packages
```
And as I'm writing this I'm wondering why I'm missing pip and pkg package lists. Ugh!

I could contribute and maintain it in my spare time. @r-darwish would you accept a more detailed design proposal as a first building block for this?

**Comment by r-darwish** [comment]
Your claims are valid, but as I said it requires so much work that it will practically be a completely new tool even if it is incorporated to Topgrade binary. I personally don’t have the interest to develop “topinstall”, but anyone wishes to do so is welcome
