### ISSUE TITLE
I think 'nix upgrade-nix' shouldn't run with '--no-system'

### ISSUE THREAD

**Issue by bbigras** [r-darwish/topgrade#88]
Currently `nix upgrade-nix` runs even if `--no-system` is specified.

`nix upgrade-nix` is for the OS right? Unless it's only the case on NixOS but not when using nix on another distro.

**Comment by r-darwish** [comment]
Interesting point. I don't support NixOS at the moment because no one asked, but if I ever do then I'll deal with `--no-system` specifically in NixOS. If you try to run Topgrade on NixOS you'll probably see "Unable to detect your Linux distribution" during the system upgrade step, but it will run Nix nonetheless.
